spring:
  application:
    name: kafka-template-service
  kafka:
    bootstrap-servers: localhost:9092
    schema-registry-url: localhost:8081
    topics:
      user-created: user-created
server:
  port: 9090
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [%traceId:%X{traceId} spanId:%X{spanId}] %msg%n"
