spring:
  application:
    name: kafka-template-service
  kafka:
    bootstrap-servers: localhost:9092
    schema-registry-url: localhost:8081
    topics:
      user-created: user-created
server:
  port: 9090