global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    static_configs:
      - targets: ['host.docker.internal:9090']  # For Docker Desktop on Windows
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s