spring:
  application:
    name: kafka-template-service
  kafka:
    bootstrap-servers: localhost:9092
    schema-registry-url: http://localhost:8081
    topics:
      user-created: user-created
    security:
      protocol: SASL_PLAINTEXT
    sasl:
      mechanism: PLAIN
      jaas:
        username: ${KAFKA_SASL_USERNAME:admin}
        password: ${KAFKA_SASL_PASSWORD:admin-secret}
server:
  port: 9090
logging:
  pattern:
    # For console logs
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:) [%X{traceId:-},%X{spanId:-}] %m%n"
    # For file logs (optional)
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID:-} [%t] %logger{40} [%X{traceId:-},%X{spanId:-}] %m%n"
management:
  tracing:
   enabled: true
   sampling:
     probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
